# Generated by Django 4.2.6 on 2023-12-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('stn_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('stn_name', models.CharField(max_length=100)),
                ('site_type', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('lat_lon_datum', models.CharField(max_length=10)),
                ('alt', models.FloatField()),
                ('alt_datum', models.CharField(max_length=10)),
                ('huc_cd', models.CharField(max_length=10)),
                ('state_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MetaFinal',
            fields=[
                ('stn_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('stn_name', models.CharField(max_length=100)),
                ('site_type', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('lat_lon_datum', models.CharField(max_length=10)),
                ('alt', models.FloatField()),
                ('alt_datum', models.CharField(max_length=10)),
                ('huc_cd', models.CharField(max_length=10)),
                ('state_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ReservoirData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stn_id', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField()),
                ('storage_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservoirDataFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stn_id', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField()),
                ('storage_value', models.FloatField()),
                ('elev', models.FloatField()),
            ],
        ),
    ]
